services:
  - type: web
    name: moohan-launch-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ADMIN_TOKEN
        sync: false
    healthCheckPath: /health
    regions:
      - ohio